[package]
name = "adventofcode2020"
version = "0.1.0"
authors = ["Tyler Hawkes <tyler.hawkes@gmail.com>"]
edition = "2018"

#[lib]
#bench = false

[dependencies]
aoc-runner = "*"
aoc-runner-derive = "*"
